name: Build (CMake)

on:
  push:
  pull_request:

jobs:
  build:
    # Si no existe CMakeLists.txt, NO corre (evita fallos mientras montas el proyecto)
    if: hashFiles('CMakeLists.txt') != ''
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -j 2

      - name: Test (optional)
        run: ctest --test-dir build --output-on-failure || true

      - name: Upload binary (artifact opcional)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dpx-binary
          path: build/** ci(build): add CMake build workflow


